# The configuration schema is defined by the service.proto file.
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto

type: google.api.Service
config_version: 3
name: api-gateway-q5t3vl3tfa-ew.a.run.app
title: grpc-test-endpoint
apis:
  - name: grpc_test.GRPCTest
usage:
  rules:
    - selector: "grpc_test.GRPCTest.*"
      allow_unregistered_calls: true
backend:
  rules:
    - selector: "grpc_test.GRPCTest.*"
      address: grpcs://grpc-test-server-q5t3vl3tfa-ew.a.run.app
